services:
  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: /api/
    ports:
      - "80:80"
    container_name: frontend
    restart: unless-stopped
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    container_name: backend
    restart: unless-stopped
